SPARQLingUnicornQGISPlugin: RectangleMapTool Class Reference
RectangleMapTool Class Reference
Public Member Functions
def __init__ (self, canvas)
def reset (self)
def canvasPressEvent (self, e)
def canvasReleaseEvent (self, e)
def canvasMoveEvent (self, e)
def showRect (self, startPoint, endPoint)
def rectangle (self)
def setRectangle (self, rect)
def deactivate (self)
Public Attributes
canvas
rubberBand
startPoint
endPoint
isEmittingPoint
point1
point2
point3
point4
Static Public Attributes
rectangleCreated = pyqtSignal()
deactivated = pyqtSignal()
string point1 = ""
string point2 = ""
string point3 = ""
string point4 = ""
bool chosen = False
Constructor & Destructor Documentation
__init__()
def __init__ (self, canvas)
     def __init__(self, canvas):
         self.canvas = canvas
         QgsMapToolEmitPoint.__init__(self, self.canvas)
         self.rubberBand = QgsRubberBand(self.canvas, QgsWkbTypes.PolygonGeometry)
         self.rubberBand.setColor(QColor(255, 0, 0, 100))
         self.rubberBand.setWidth(2)
         self.reset()
Member Function Documentation
canvasMoveEvent()
def canvasMoveEvent (self, e)
References RectangleMapTool.endPoint, RectangleMapTool.isEmittingPoint, RectangleMapTool.showRect(), and RectangleMapTool.startPoint.
     def canvasMoveEvent(self, e):
         if not self.isEmittingPoint:
             return
         self.endPoint = self.toMapCoordinates(e.pos())
         self.showRect(self.startPoint, self.endPoint)
canvasPressEvent()
def canvasPressEvent (self, e)
References RectangleMapTool.endPoint, RectangleMapTool.isEmittingPoint, RectangleMapTool.showRect(), and RectangleMapTool.startPoint.
     def canvasPressEvent(self, e):
         self.startPoint = self.toMapCoordinates(e.pos())
         self.endPoint = self.startPoint
         self.isEmittingPoint = True
         self.showRect(self.startPoint, self.endPoint)
canvasReleaseEvent()
def canvasReleaseEvent (self, e)
References RectangleMapTool.isEmittingPoint, RectangleMapTool.rectangle(), and RectangleMapTool.rectangleCreated.
     def canvasReleaseEvent(self, e):
         self.isEmittingPoint = False
         if self.rectangle() is not None:
             self.rectangleCreated.emit()
deactivate()
def deactivate (self)
References RectangleMapTool.deactivated.
     def deactivate(self):
         QgsMapTool.deactivate(self)
         self.deactivated.emit()
rectangle()
def rectangle (self)
References RectangleMapTool.endPoint, and RectangleMapTool.startPoint.
Referenced by RectangleMapTool.canvasReleaseEvent(), and RectangleMapTool.setRectangle().
     def rectangle(self):
         if self.startPoint is None or self.endPoint is None:
             return None
         elif self.startPoint.x() == self.endPoint.x() or \
                 self.startPoint.y() == self.endPoint.y():
             return None
         return QgsRectangle(self.startPoint, self.endPoint)
reset()
def reset (self)
Referenced by RectangleMapTool.setRectangle(), and RectangleMapTool.showRect().
     def reset(self):
         self.startPoint = self.endPoint = None
         self.isEmittingPoint = False
         self.rubberBand.reset(QgsWkbTypes.PolygonGeometry)
setRectangle()
def setRectangle (self, rect)
References RectangleMapTool.endPoint, RectangleMapTool.rectangle(), RectangleMapTool.reset(), RectangleMapTool.showRect(), and RectangleMapTool.startPoint.
     def setRectangle(self, rect):
         if rect == self.rectangle():
             return False
         if rect is None:
             self.reset()
         else:
             self.startPoint = QgsPointXY(rect.xMaximum(), rect.yMaximum())
             self.endPoint = QgsPointXY(rect.xMinimum(), rect.yMinimum())
             self.showRect(self.startPoint, self.endPoint)
         return True
showRect()
def showRect (self, startPoint, endPoint)
References RectangleMapTool.reset(), and RectangleMapTool.rubberBand.
Referenced by RectangleMapTool.canvasMoveEvent(), RectangleMapTool.canvasPressEvent(), and RectangleMapTool.setRectangle().
     def showRect(self, startPoint, endPoint):
         self.rubberBand.reset(QgsWkbTypes.PolygonGeometry)
         if startPoint.x() == endPoint.x() or startPoint.y() == endPoint.y():
             return
         self.point1 = QgsPointXY(startPoint.x(), startPoint.y())
         self.point2 = QgsPointXY(startPoint.x(), endPoint.y())
         self.point3 = QgsPointXY(endPoint.x(), endPoint.y())
         self.point4 = QgsPointXY(endPoint.x(), startPoint.y())
         self.rubberBand.addPoint(self.point1, False)
         self.rubberBand.addPoint(self.point2, False)
         self.rubberBand.addPoint(self.point3, False)
         # True to update canvas
         self.rubberBand.addPoint(self.point4, True)
         self.rubberBand.show()
         chosen=True
Member Data Documentation
canvas
canvas
chosen
bool chosen = False static
deactivated
deactivated = pyqtSignal() static
Referenced by RectangleMapTool.deactivate().
endPoint
endPoint
Referenced by RectangleMapTool.canvasMoveEvent(), RectangleMapTool.canvasPressEvent(), RectangleMapTool.rectangle(), and RectangleMapTool.setRectangle().
isEmittingPoint
isEmittingPoint
Referenced by RectangleMapTool.canvasMoveEvent(), RectangleMapTool.canvasPressEvent(), and RectangleMapTool.canvasReleaseEvent().
point1 [1/2]
string point1 = "" static
point1 [2/2]
point1
point2 [1/2]
string point2 = "" static
point2 [2/2]
point2
point3 [1/2]
string point3 = "" static
point3 [2/2]
point3
point4 [1/2]
string point4 = "" static
point4 [2/2]
point4
rectangleCreated
rectangleCreated = pyqtSignal() static
Referenced by RectangleMapTool.canvasReleaseEvent().
rubberBand
rubberBand
Referenced by RectangleMapTool.showRect().
startPoint
startPoint
Referenced by RectangleMapTool.canvasMoveEvent(), RectangleMapTool.canvasPressEvent(), RectangleMapTool.rectangle(), and RectangleMapTool.setRectangle().