SPARQLingUnicornQGISPlugin: CircleMapTool Class Reference
CircleMapTool Class Reference
Public Member Functions
def __init__ (self, iface, segments)
def canvasPressEvent (self, e)
def canvasMoveEvent (self, e)
def canvasReleaseEvent (self, e)
def reset (self)
def deactivate (self)
def rbcircle (self, rb, center, edgePoint, N)
Public Attributes
canvas
iface
status
segments
rb
center
Static Public Attributes
selectionDone = pyqtSignal()
move = pyqtSignal()
Detailed Description
Outil de sélection par cercle, tiré de selectPlusFr
Constructor & Destructor Documentation
__init__()
def __init__ (self, iface, segments)
     def __init__(self, iface, segments):
         canvas = iface
         QgsMapTool.__init__(self, canvas)
         self.canvas = canvas
         self.iface = iface
         self.status = 0
         self.segments = segments
         self.rb = QgsRubberBand(self.canvas, QgsWkbTypes.PolygonGeometry)
         self.rb.setColor(QColor(255, 0, 0, 100))
         return None
Member Function Documentation
canvasMoveEvent()
def canvasMoveEvent (self, e)
     def canvasMoveEvent(self, e):
         if not self.status == 1:
             return
         # construct a circle with N segments
         cp = self.toMapCoordinates(e.pos())
         self.rbcircle(self.rb, self.center, cp, self.segments)
         self.rb.show()
         self.move.emit()
References CircleMapTool.center, CircleMapTool.move, CircleMapTool.rb, CircleMapTool.rbcircle(), CircleMapTool.segments, and CircleMapTool.status.
canvasPressEvent()
def canvasPressEvent (self, e)
     def canvasPressEvent(self, e):
         if not e.button() == Qt.LeftButton:
             return
         self.status = 1
         self.center = self.toMapCoordinates(e.pos())
         self.rbcircle(self.rb, self.center, self.center, self.segments)
         return
References CircleMapTool.status.
canvasReleaseEvent()
def canvasReleaseEvent (self, e)
La sélection est faîte
     def canvasReleaseEvent(self, e):
         '''La sélection est faîte'''
         if not e.button() == Qt.LeftButton:
             return None
         self.status = 0
         if self.rb.numberOfVertices() > 3:
             self.selectionDone.emit()
         else:
             radius=2
                         #, ok = QInputDialog.getDouble(self.iface.mainWindow(), tr('Radius'),tr('Give a radius in m:'), min=0)
             if radius > 0:
                 cp = self.toMapCoordinates(e.pos())
                 cp.setX(cp.x() + radius)
                 self.rbcircle(self.rb, self.toMapCoordinates(
                     e.pos()), cp, self.segments)
                 self.rb.show()
                 self.selectionDone.emit()
         return None
References CircleMapTool.rb, CircleMapTool.rbcircle(), CircleMapTool.segments, CircleMapTool.selectionDone, and CircleMapTool.status.
deactivate()
def deactivate (self)
     def deactivate(self):
         self.rb.reset(True)
         QgsMapTool.deactivate(self)
References CircleMapTool.rb, and CircleMapTool.reset().
rbcircle()
def rbcircle (self, rb, center, edgePoint, N)
Fonction qui affiche une rubberband sous forme de cercle
     def rbcircle(self,rb, center, edgePoint, N):
         '''Fonction qui affiche une rubberband sous forme de cercle'''
         r = sqrt(center.sqrDist(edgePoint))
         self.rb.reset(QgsWkbTypes.PolygonGeometry)
         for itheta in range(N + 1):
             theta = itheta * (2.0 * pi / N)
             rb.addPoint(QgsPointXY(center.x() + r * cos(theta),
                                center.y() + r * sin(theta)))
         return
References CircleMapTool.rb, and CircleMapTool.reset().
Referenced by CircleMapTool.canvasMoveEvent(), and CircleMapTool.canvasReleaseEvent().
reset()
def reset (self)
     def reset(self):
         self.status = 0
         self.rb.reset(True)
References CircleMapTool.rb, and CircleMapTool.status.
Referenced by PolygonMapTool.canvasPressEvent(), CircleMapTool.deactivate(), CircleMapTool.rbcircle(), and RectangleMapTool.setRectangle().
Member Data Documentation
canvas
canvas
center
center
Referenced by CircleMapTool.canvasMoveEvent().
iface
iface
Referenced by SPAQLunicorn.add_action(), SPAQLunicorn.initGui(), and SPAQLunicorn.unload().
move
move = pyqtSignal() static
Referenced by CircleMapTool.canvasMoveEvent(), and PolygonMapTool.canvasMoveEvent().
rb
rb
Referenced by CircleMapTool.canvasMoveEvent(), PolygonMapTool.canvasMoveEvent(), PolygonMapTool.canvasPressEvent(), CircleMapTool.canvasReleaseEvent(), CircleMapTool.deactivate(), PolygonMapTool.deactivate(), PolygonMapTool.keyPressEvent(), CircleMapTool.rbcircle(), CircleMapTool.reset(), and PolygonMapTool.reset().
segments
segments
Referenced by CircleMapTool.canvasMoveEvent(), and CircleMapTool.canvasReleaseEvent().
selectionDone
selectionDone = pyqtSignal() static
Referenced by PolygonMapTool.canvasPressEvent(), and CircleMapTool.canvasReleaseEvent().
status
status
Referenced by CircleMapTool.canvasMoveEvent(), PolygonMapTool.canvasMoveEvent(), CircleMapTool.canvasPressEvent(), PolygonMapTool.canvasPressEvent(), CircleMapTool.canvasReleaseEvent(), CircleMapTool.reset(), and PolygonMapTool.reset().