SPARQLingUnicornQGISPlugin: LoginWindow Class Reference
LoginWindow Class Reference
Public Member Functions
def __init__ (self, app)
def __init__ (self, app, authurl, interceptor)
def callable (self, data)
Public Attributes
nam
app
interceptor
html
Static Public Attributes
logged_in = QtCore.pyqtSignal(['QString'])
Private Member Functions
def _loadFinished (self, result)
Constructor & Destructor Documentation
__init__() [1/2]
def __init__ (self, app)
     def __init__(self, app):
         super(LoginWindow, self).__init__()
         self.nam = self.page()
         self.app = app
         self.setUrl(QUrl(AuthUrl))
         self.show()
         self.loadFinished.connect(self._loadFinished)
         interceptor = RequestInterceptor(self.app)
 =======
Referenced by LoginWindow.__init__().
__init__() [2/2]
def __init__ (self, app, authurl, interceptor)
     def __init__(self, app, authurl,interceptor):
         super(LoginWindow, self).__init__()
         self.nam = self.page()
         self.app = app
         self.setUrl(QUrl(authurl))
         self.show()
         self.loadFinished.connect(self._loadFinished)
         self.interceptor = interceptor
 >>>>>>> 62eabd13feb11502469f2bb0c5c2a2fb1328b89b
         self.page().profile().setRequestInterceptor(interceptor)
         sys.exit(app.exec_())
References LoginWindow.__init__(), LoginWindow._loadFinished(), LoginWindow.app, and LoginWindow.nam.
Member Function Documentation
_loadFinished()
def _loadFinished (self, result) private
     def _loadFinished(self, result):
         self.page().toHtml(self.callable)
References LoginWindow.callable().
Referenced by LoginWindow.__init__().
callable()
def callable (self, data)
     def callable(self, data):
         self.html = data
 <<<<<<< HEAD
 =======
 >>>>>>> 62eabd13feb11502469f2bb0c5c2a2fb1328b89b
Referenced by LoginWindow._loadFinished().
Member Data Documentation
app
app
Referenced by LoginWindow.__init__(), RequestInterceptor.__init__(), and GitlabRequestInterceptor.interceptRequest().
html
html
interceptor
interceptor
logged_in
logged_in = QtCore.pyqtSignal(['QString']) static
nam
nam
Referenced by LoginWindow.__init__().