SPARQLingUnicornQGISPlugin: sparqlunicornGoesGIS.util.sparqlhighlighter Namespace Reference
sparqlunicornGoesGIS.util.sparqlhighlighter Namespace Reference
Classes
class SPARQLHighlighter
Functions
def format (color, style='')
Variables
dictionary STYLES
Function Documentation
format()
def sparqlunicornGoesGIS.util.sparqlhighlighter.format (color, style = '')
Return a QTextCharFormat with the given attributes.
 def format(color, style=''):
     """Return a QTextCharFormat with the given attributes.
     """
     _color = QColor()
     _color.setNamedColor(color)
     _format = QTextCharFormat()
     _format.setForeground(_color)
     if 'bold' in style:
         _format.setFontWeight(QFont.Bold)
     if 'italic' in style:
         _format.setFontItalic(True)
     return _format
Referenced by BBOXDialog.geocode(), RequestInterceptor.interceptRequest(), GitlabRequestInterceptor.interceptRequest(), sparqlunicornGoesGIS.plugin_upload.main(), QueryLayerTask.run(), WhatToEnrichQueryTask.run(), LoadGraphTask.run(), SearchTask.run(), GeoConceptsQueryTask.run(), DetectTripleStoreTask.run(), EnrichmentQueryTask.run(), and ConvertCRSTask.run().
Variable Documentation
STYLES
dictionary STYLES
Initial value:
 =  {
     'keyword': format('#b32424'),
     'operator': format('black'),
     'error': format('red'),
     'brace': format('black'),
     'defclass': format('#14866d'),
     'uri': format('#2a4b8d'),
     'prefixcls': format('#14866d'),
     'string': format('#ac6600'),
     'string2': format('darkMagenta'),
     'comment': format('#72777d'),
     'self': format('blue', 'italic'),
     'numbers': format('black'),
 }