SPARQLingUnicornQGISPlugin: sparqlunicornGoesGIS.util.sparqlhighlighter Namespace Reference
sparqlunicornGoesGIS.util.sparqlhighlighter Namespace Reference
Classes
class SPARQLHighlighter
Functions
def format (color, style='')
Variables
dictionary STYLES
Function Documentation
format()
def sparqlunicornGoesGIS.util.sparqlhighlighter.format (color, style = '')
Return a QTextCharFormat with the given attributes.
 def format(color, style=''):
     """Return a QTextCharFormat with the given attributes.
     """
     _color = QColor()
     _color.setNamedColor(color)
     _format = QTextCharFormat()
     _format.setForeground(_color)
     if 'bold' in style:
         _format.setFontWeight(QFont.Bold)
     if 'italic' in style:
         _format.setFontItalic(True)
     return _format
Referenced by DataSchemaQueryTask.__init__(), WhatToEnrichQueryTask.__init__(), SPARQLunicorn.endpointselectaction(), SPARQLUtils.executeQuery(), InstanceAmountQueryTask.finished(), FindStyleQueryTask.finished(), InstanceListQueryTask.finished(), GetStyleQueryTask.finished(), ClassTreeQueryTask.finished(), BBOXDialog.geocode(), InstanceDataDialog.getAttributes(), DataSchemaDialog.getAttributeStatistics(), OAuthConfiguration.getAuthUrl(), SPARQLunicorn.getGeoCollectionInstances(), SPARQLunicornDialog.iterateTree(), SPARQLUtils.loadGraph(), sparqlunicornGoesGIS.plugin_upload.main(), InstanceAmountQueryTask.run(), InstanceListQueryTask.run(), GetStyleQueryTask.run(), FindStyleQueryTask.run(), InstanceQueryTask.run(), DataSampleQueryTask.run(), SubClassQueryTask.run(), QueryLayerTask.run(), GraphValidationTask.run(), SearchTask.run(), WhatToEnrichQueryTask.run(), DataSchemaQueryTask.run(), GeoConceptsQueryTask.run(), DetectTripleStoreTask.run(), GeoCollectionsQueryTask.run(), EnrichmentQueryTask.run(), ClassTreeQueryTask.run(), ConvertCRSTask.run(), and SPARQLunicornDialog.saveTreeToRDF().
Variable Documentation
STYLES
dictionary STYLES
Initial value:
 =  {
     'keyword': format('#b32424'),
     'operator': format('black'),
     'error': format('red'),
     'brace': format('black'),
     'defclass': format('#14866d'),
     'uri': format('#2a4b8d'),
     'prefixcls': format('#14866d'),
     'string': format('#ac6600'),
     'string2': format('darkMagenta'),
     'comment': format('#72777d'),
     'self': format('blue', 'italic'),
     'numbers': format('black'),
 }