SPARQLingUnicornQGISPlugin: QJsonTreeItem Class Reference
QJsonTreeItem Class Reference
Public Member Functions
def __init__ (self, parent=None)
def appendChild (self, item)
def child (self, row)
def parent (self)
def childCount (self)
def row (self)
def key (self)
def key (self, key)
def value (self)
def value (self, value)
def type (self)
def type (self, typ)
def load (self, value, parent=None, sort=True)
Private Attributes
_parent
_key
_value
_type
_children
Constructor & Destructor Documentation
__init__()
def __init__ (self, parent = None)
     def __init__(self, parent=None):
         self._parent = parent
         self._key = ""
         self._value = ""
         self._type = None
         self._children = list()
Member Function Documentation
appendChild()
def appendChild (self, item)
     def appendChild(self, item):
         self._children.append(item)
References QJsonTreeItem._children.
child()
def child (self, row)
     def child(self, row):
         return self._children[row]
References QJsonTreeItem._children.
childCount()
def childCount (self)
     def childCount(self):
         return len(self._children)
References QJsonTreeItem._children.
key() [1/2]
def key (self)
     def key(self):
         return self._key
References QJsonTreeItem._key.
Referenced by QJsonTreeItem.key().
key() [2/2]
def key (self, key)
     def key(self, key):
         self._key = key
References QJsonTreeItem._key, and QJsonTreeItem.key().
load()
def load (self, value, parent = None, sort = True)
     def load(self, value, parent=None, sort=True):
         rootItem = QJsonTreeItem(parent)
         rootItem.key = "root"
         if isinstance(value, dict):
             items = (
                 sorted(value.items())
                 if sort else value.items()
             )
             for key, value in items:
                 child = self.load(value, rootItem)
                 child.key = key
                 child.type = type(value)
                 rootItem.appendChild(child)
         elif isinstance(value, list):
             for index, value in enumerate(value):
                 child = self.load(value, rootItem)
                 child.key = index
                 child.type = type(value)
                 rootItem.appendChild(child)
         else:
             rootItem.value = value
             rootItem.type = type(value)
         return rootItem
References QJsonTreeItem.load(), and QJsonTreeItem.type().
Referenced by QJsonModel.clear(), and QJsonTreeItem.load().
parent()
def parent (self)
     def parent(self):
         return self._parent
References QJsonTreeItem._parent.
row()
def row (self)
     def row(self):
         return (
             self._parent._children.index(self)
             if self._parent else 0
         )
References QJsonTreeItem._parent.
type() [1/2]
def type (self)
     def type(self):
         return self._type
References QJsonTreeItem._type.
Referenced by QJsonTreeItem.load(), and QJsonTreeItem.type().
type() [2/2]
def type (self, typ)
     def type(self, typ):
         self._type = typ
References QJsonTreeItem._type, and QJsonTreeItem.type().
value() [1/2]
def value (self)
     def value(self):
         return self._value
References QJsonTreeItem._value.
Referenced by QJsonTreeItem.value().
value() [2/2]
def value (self, value)
     def value(self, value):
         self._value = value
References QJsonTreeItem._value, and QJsonTreeItem.value().
Member Data Documentation
_children
_children private
Referenced by QJsonTreeItem.appendChild(), QJsonTreeItem.child(), and QJsonTreeItem.childCount().
_key
_key private
Referenced by QJsonTreeItem.key().
_parent
_parent private
Referenced by QJsonTreeItem.parent(), and QJsonTreeItem.row().
_type
_type private
Referenced by QJsonTreeItem.type().
_value
_value private
Referenced by QJsonTreeItem.value().