from rdflib.namespace import DefinedNamespace, Namespace
from rdflib.term import URIRef

class GEOCRS(DefinedNamespace):

    #3DCoordinateSystem: URIRef
    AitoffProjection: URIRef
    AlbersEqualAreaProjection: URIRef
    AmericanPolyconicProjection: URIRef
    AreaOfUse: URIRef
    AxisDirection: URIRef
    BoundCRS: URIRef
    BonneProjection: URIRef
    CRS: URIRef
    CadastreMap: URIRef
    CartesianCoordinateSystem: URIRef
    CassiniProjection: URIRef
    CoastalHydrography: URIRef
    CollignonProjection: URIRef
    ColombiaUrbanProjection: URIRef
    CompoundCRS: URIRef
    CoordinateConcatenatedOperation: URIRef
    CoordinateConversionOperation: URIRef
    CoordinateOperation: URIRef
    CoordinateTransformationOperation: URIRef
    CoordinateSystemAxis: URIRef
    CylindricalEqualArea: URIRef
    CylindricalProjection: URIRef
    Datum: URIRef
    Drilling: URIRef
    DynamicVerticalReferenceFrame: URIRef
    EllipsoidalCoordinateSystem: URIRef
    EngineeringSurvey: URIRef
    EqualEarthProjection: URIRef
    EquidistantConicProjection: URIRef
    EquidistantCylindricalProjection: URIRef
    Ellipsoid: URIRef
    GeocentricCRS: URIRef
    Geocentric: URIRef
    GeodeticReferenceFrame: URIRef
    GeographicCRS: URIRef
    Geodesy: URIRef
    Geoid: URIRef
    GnomonicProjection: URIRef
    Grid: URIRef
    Hydrography: URIRef
    Krovak: URIRef
    LabordeProjection: URIRef
    LambertAzimuthalEqualArea: URIRef
    LambertConformalConicProjection: URIRef
    LambertEqualAreaConic: URIRef
    LatLonProjection: URIRef
    LonLatProjection: URIRef
    LoximuthalProjection: URIRef
    MercatorProjection: URIRef
    MillerProjection: URIRef
    MollweideProjection: URIRef
    NicolosiGlobularProjection: URIRef
    ObliqueMercatorProjection: URIRef
    ObliqueStereographicProjection: URIRef
    OffshoreEngineering: URIRef
    OilAndGasExploration: URIRef
    OrthographicProjection: URIRef
    OtherCoordinateOperation: URIRef
    NaturalEarthProjection: URIRef
    NauticalChart: URIRef
    PrimeMeridian: URIRef
    ProjectedCRS: URIRef
    PseudoCylindricalProjection: URIRef
    PlanarCoordinateSystem: URIRef
    RectangularPolyconicProjection: URIRef
    RobinsonProjection: URIRef
    SatelliteNavigation: URIRef
    SinusoidalProjection: URIRef
    SpatialReferencing: URIRef
    Sphere: URIRef
    SatelliteSurvey: URIRef
    StereographicProjection: URIRef
    SRSApplication: URIRef
    TransverseMercatorProjection: URIRef
    TopographicMap: URIRef
    UniversalTransverseMercatorProjection: URIRef
    VerticalCoordinateSystem: URIRef
    VerticalCRS: URIRef
    VerticalReferenceFrame: URIRef

    abbreviation: URIRef
    accuracy: URIRef
    approximates: URIRef
    area_of_use: URIRef
    asWKT: URIRef
    asProj4: URIRef
    asProjJSON: URIRef
    axis: URIRef
    coordinateOperation: URIRef
    coordinateSystem: URIRef
    datum: URIRef
    direction: URIRef
    ellipsoid: URIRef
    ellipse: URIRef
    epsgCode: URIRef
    eccentricity: URIRef
    flatteningParameter: URIRef
    has_ballpark_transformation: URIRef
    includesSRS: URIRef
    inverse_flattening: URIRef
    isApplicableTo: URIRef
    isBound: URIRef
    isGeocentric: URIRef
    isGeographic: URIRef
    isProjected: URIRef
    isSphere: URIRef
    is_semi_minor_computed: URIRef
    isVertical: URIRef
    grid: URIRef
    longitude: URIRef
    method_name: URIRef
    open_license: URIRef
    operation: URIRef
    primeMeridian: URIRef
    scope: URIRef
    semiMajorAxis: URIRef
    semiMinorAxis: URIRef
    sourceCRS: URIRef
    targetCRS: URIRef
    wktLiteral: URIRef
    unit: URIRef
    unit_auth_code: URIRef
    unit_code: URIRef
    unit_conversion_factor: URIRef
    usage: URIRef
    utm_zone: URIRef


    _NS = Namespace("http://www.opengis.net/ont/crs/")