var searchData=
[
  ['safetranslationstest_0',['SafeTranslationsTest',['../a01377.html',1,'sparqlunicornGoesGIS::test::test_translations']]],
  ['searchdialog_1',['SearchDialog',['../a01197.html',1,'sparqlunicornGoesGIS::dialogs::util::searchdialog']]],
  ['searchtask_2',['SearchTask',['../a01333.html',1,'sparqlunicornGoesGIS::tasks::query::searchtask']]],
  ['settingsdialog_3',['SettingsDialog',['../a01085.html',1,'sparqlunicornGoesGIS::dialogs::conf::settingsdialog']]],
  ['solidexporter_4',['SolidExporter',['../a01441.html',1,'sparqlunicornGoesGIS::util::export::api::solidexporter']]],
  ['spaqlunicorndialogtest_5',['spaqlunicorndialogtest',['../a01369.html',1,'SPAQLunicornDialogTest'],['../a01373.html',1,'SPAQLunicornDialogTest']]],
  ['sparqlcompleter_6',['sparqlcompleter',['../a01541.html',1,'SPARQLCompleter'],['../a01613.html',1,'SPARQLCompleter']]],
  ['sparqlhighlighter_7',['SPARQLHighlighter',['../a01609.html',1,'sparqlunicornGoesGIS::util::ui::sparqlhighlighter']]],
  ['sparqlpage_8',['SPARQLPage',['../a01529.html',1,'sparqlunicornGoesGIS::util::export::pages::sparqlpage']]],
  ['sparqlunicorn_9',['SPARQLunicorn',['../a01213.html',1,'sparqlunicornGoesGIS::sparql_unicorn']]],
  ['sparqlunicorndialog_10',['SPARQLunicornDialog',['../a01129.html',1,'sparqlunicornGoesGIS::dialogs::sparql_unicorn_dialog']]],
  ['sparqlutils_11',['SPARQLUtils',['../a01573.html',1,'sparqlunicornGoesGIS::util::sparqlutils']]],
  ['stringmatching_12',['StringMatching',['../a01565.html',1,'sparqlunicornGoesGIS::util::matchingtools']]],
  ['styleobject_13',['StyleObject',['../a01577.html',1,'sparqlunicornGoesGIS::util::style::styleobject']]],
  ['styleutils_14',['StyleUtils',['../a01581.html',1,'sparqlunicornGoesGIS::util::style::styleutils']]],
  ['subclassquerytask_15',['SubClassQueryTask',['../a01305.html',1,'sparqlunicornGoesGIS::tasks::query::discovery::subclassquerytask']]]
];
