SPARQLing Unicorn QGIS Plugin: SPARQLCompleter Class Reference
SPARQLCompleter Class Reference
Public Member Functions
__init__ (self, autocomplete, parent=None)
setModel (self, model)
updateModel (self)
setHighlighted (self, text)
getSelected (self)
Public Attributes
source_model
lastSelected
Static Public Attributes
insertText = QtCore.pyqtSignal(str)
Constructor & Destructor Documentation
__init__()
__init__ (self, autocomplete, parent = None)
    def __init__(self, autocomplete, parent=None):
        QCompleter.__init__(self, autocomplete, parent)
        self.setCompletionMode(QCompleter.CompletionMode.PopupCompletion)
        self.setFilterMode(Qt.MatchFlag.MatchContains)
        self.source_model=None
        self.setModel(QStandardItemModel())
        # self.highlighted.connect(self.setHighlighted)
Member Function Documentation
getSelected()
getSelected (self)
    def getSelected(self):
        return self.lastSelected
References SPARQLCompleter.lastSelected.
setHighlighted()
setHighlighted (self, text)
    def setHighlighted(self, text):
        self.lastSelected = text
setModel()
setModel (self, model)
    def setModel(self, model):
        self.source_model = model
        super(SPARQLCompleter, self).setModel(self.source_model)
References SPARQLCompleter.setModel(), and SPARQLCompleter.source_model.
Referenced by SPARQLCompleter.setModel(), and SPARQLCompleter.updateModel().
updateModel()
updateModel (self)
    def updateModel(self):
        local_completion_prefix = self.local_completion_prefix
        class InnerProxyModel(QSortFilterProxyModel):
            def filterAcceptsRow(self, sourceRow, sourceParent):
                index0 = self.sourceModel().index(sourceRow, 0, sourceParent)
                self.zoomToCoordinates(index0)
                return local_completion_prefix.lower() in self.sourceModel().data(index0).lower()
        proxy_model = InnerProxyModel()
        proxy_model.setSourceModel(self.source_model)
        super(SPARQLCompleter, self).setModel(proxy_model)
References SPARQLCompleter.setModel(), and SPARQLCompleter.source_model.
Member Data Documentation
insertText
insertText = QtCore.pyqtSignal(str) static
lastSelected
lastSelected
Referenced by SPARQLCompleter.getSelected().
source_model
source_model
Referenced by SPARQLCompleter.setModel(), and SPARQLCompleter.updateModel().